@echo off
rem ScenePlay Remote self-hosted installer - Windows 10/11.
rem Creates .venv, installs the pinned dependencies, and generates a .env with
rem strong random secrets. Safe to re-run: an existing .env is never touched,
rem dependencies are just refreshed. Companion: start.bat
setlocal
cd /d "%~dp0"

set "PY=py -3"
%PY% --version >nul 2>nul || set "PY=python"
%PY% --version >nul 2>nul || (
    echo ERROR: Python not found.
    echo Install Python 3.10 or newer from https://www.python.org/downloads/
    echo IMPORTANT: tick "Add python.exe to PATH" in the installer.
    pause
    exit /b 1
)
%PY% -c "import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)" || (
    echo ERROR: Python 3.10 or newer is required.
    %PY% --version
    pause
    exit /b 1
)
echo ==^> Using:
%PY% --version

echo ==^> Creating virtual environment (.venv)...
%PY% -m venv .venv || (echo ERROR: could not create .venv & pause & exit /b 1)

echo ==^> Installing dependencies (takes a few minutes the first time)...
.venv\Scripts\python -m pip install --quiet --upgrade pip
.venv\Scripts\pip install --quiet -r requirements.txt || (
    echo ERROR: dependency install failed - check your internet connection.
    pause
    exit /b 1
)

if exist .env (
    echo ==^> Existing .env found - keeping your current secrets.
) else (
    echo ==^> Generating .env with fresh random secrets...
    .venv\Scripts\python -c "import secrets; open('.env','w').write('# Generated by install.bat - see .env.example for optional settings.\nRELAY_SECRET=%%s\nJWT_SECRET=%%s\nDATABASE_URL=sqlite:///./relay.db\n# PORT=8000\n' %% (secrets.token_hex(32), secrets.token_hex(32)))"
)

echo.
echo ================================================================
echo  ScenePlay Remote is installed.
echo.
echo  Start it:       double-click start.bat
echo  Player portal:  http://localhost:8000/
echo.
echo  In ScenePlay's TTRPG relay admin enter this computer's IP as
echo  the Relay URL (http://YOUR-IP:8000) and the RELAY_SECRET value
echo  below, then enable the relay and press Sync.
echo.
findstr /b "RELAY_SECRET=" .env
echo ================================================================
pause
