#!/usr/bin/env bash
# ScenePlay Remote self-hosted installer — Linux / Raspberry Pi / macOS.
# Creates .venv, installs the pinned dependencies, and generates a .env with
# strong random secrets. Safe to re-run: an existing .env is never touched,
# dependencies are just refreshed. Companion: ./start.sh
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 not found."
    echo "Install it first — Debian/Ubuntu/Raspberry Pi OS:  sudo apt install python3 python3-venv"
    exit 1
fi
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' || {
    echo "ERROR: Python 3.10 or newer is required (found $(python3 --version 2>&1))."
    exit 1
}
echo "==> Using $(python3 --version)"

echo "==> Creating virtual environment (.venv)..."
python3 -m venv .venv

echo "==> Installing dependencies (takes a few minutes the first time)..."
./.venv/bin/pip install --quiet --upgrade pip
./.venv/bin/pip install --quiet -r requirements.txt

if [ -f .env ]; then
    echo "==> Existing .env found — keeping your current secrets."
else
    echo "==> Generating .env with fresh random secrets..."
    ./.venv/bin/python - <<'PYEOF'
import secrets
with open(".env", "w") as f:
    f.write(
        "# Generated by install.sh — see .env.example for optional settings.\n"
        f"RELAY_SECRET={secrets.token_hex(32)}\n"
        f"JWT_SECRET={secrets.token_hex(32)}\n"
        "DATABASE_URL=sqlite:///./relay.db\n"
        "# PORT=8000\n"
    )
PYEOF
fi

RELAY_SECRET_VALUE=$(grep '^RELAY_SECRET=' .env | head -1 | cut -d= -f2-)
IP=$(hostname -I 2>/dev/null | awk '{print $1}')
IP=${IP:-"<this-computer's-IP>"}

echo
echo "================================================================"
echo " ScenePlay Remote is installed."
echo
echo " Start it:            ./start.sh"
echo " Player portal:       http://${IP}:8000/"
echo
echo " In ScenePlay's TTRPG relay admin enter:"
echo "   Relay URL:     http://${IP}:8000"
echo "   Relay secret:  ${RELAY_SECRET_VALUE}"
echo " then enable the relay and press Sync."
echo "================================================================"
